// alex_s/ap-vue/src/admin/posts/post-manage/index.vue
<template>
  <div class="post-manage">
    <h2 class="page-title">Posts</h2>

    <Form
      class="form"
      @submit="submit"
      :validation-schema="schema"
      :initial-values="{
        title: post?.title,
        excerpt: post?.excerpt,
        description: post?.description,
      }"
      v-slot="{ errors }"
    >
      <div class="card">
        <div class="card__header">
          <div class="card__title">{{ title }}</div>
        </div>

        <div class="card__body">
          <div class="row">
            <div class="col-lg post-manage__image-wrap">
              <div class="form__upload">
                <div class="form__upload__image">
                  <div
                    class="form__upload__image__img"
                    :style="{
                      backgroundImage: `url(${
                        postImagePreview ? postImagePreview : postImage
                      })`,
                    }"
                  ></div>
                  <button
                    v-if="postImage || postImagePreview"
                    type="button"
                    class="form__upload__image__clear"
                    @click="clearImage"
                  >
                    <i class="las la-times"></i>
                  </button>
                </div>
                <div class="form__upload__btn">
                  <input
                    type="file"
                    id="image"
                    accept=".png,.jpg"
                    @change="uploadPreview"
                  />
                  <label type="button" for="image" class="btn btn--gray">
                    Upload Image
                  </label>
                </div>
                <div
                  class="form__upload__description"
                  :class="{
                    'form__upload__description--danger': postImageOverSize,
                  }"
                >
                  Maximum upload image size: <span>1MB</span>
                </div>
              </div>
            </div>
            <div class="col-lg">
              <div class="form__group form__group--required">
                <label class="form__label" for="title">Title</label>
                <Field
                  type="text"
                  name="title"
                  id="title"
                  class="form__element"
                  :class="{ 'is-invalid': errors.title }"
                />
              </div>

              <div class="form__group">
                <label class="form__label" for="excerpt">Excerpt</label>
                <Field
                  type="text"
                  name="excerpt"
                  id="excerpt"
                  class="form__element"
                  :class="{ 'is-invalid': errors.excerpt }"
                />
              </div>
            </div>
          </div>
          <br />
          <div class="form__group form__group--required">
            <label class="form__label" for="description">Description</label>
            <Field name="description" v-slot="{ field }">
              <textarea
                v-bind="field"
                id="description"
                class="form__element"
                :class="{ 'is-invalid': errors.description }"
              ></textarea>
            </Field>
          </div>
        </div>

        <div class="card__footer">
          <div class="btn-group">
            <button :disabled="isSubmited" class="btn btn--blue" type="submit">
              {{ submitBtnTitle }}
            </button>
            <router-link to="/admin/posts" custom v-slot="{ href, navigate }">
              <a
                v-if="!isSubmited"
                :href="href"
                class="btn btn--cancel"
                @click="navigate"
              >
                Cancel
              </a>
              <button
                v-if="isSubmited"
                type="button"
                class="btn btn--cancel btn--disabled"
              >
                Cancel
              </button>
            </router-link>
          </div>
        </div>
      </div>
    </Form>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onUpdated, onMounted } from "vue";
import { useRouter } from "vue-router";
import { useStore, mapActions } from "vuex";
import GlobalService from "@/servises/global";
import { Form, Field } from "vee-validate";
import * as Yup from "yup";

interface IForm {
  title: string;
  excerpt: string;
  description: string;
}

export default defineComponent({
  components: {
    Form,
    Field,
  },
  setup() {
    const store = useStore();
    const router = useRouter();

    const schema = Yup.object().shape({
      title: Yup.string().required("Name is required"),
      excerpt: Yup.string().required("Surname is required"),
      description: Yup.string().required("Occupation is required"),
    });

    const title = ref("");
    const submitBtnTitle = ref("");

    const noImage = computed(() =>
      require("@/assets/images/site/no-image-post-white.svg")
    );
    const postImagePreview = ref();
    const postImage = ref();
    const postImageFile = ref();
    const postImageDelete = ref(false);
    const postImageOverSize = ref(false);
    const post = ref({
      uid: "",
      title: "",
      excerpt: "",
      description: "",
      photoURL: "",
      owner: "",
      createdAt: "",
    });

    const isSubmited = ref(false);

    const computedRouteName = () => {
      if (router.currentRoute.value.name === "post-add") {
        title.value = "Add New Post";
        submitBtnTitle.value = "Create";
        postImage.value = noImage.value;
      } else if (router.currentRoute.value.name === "post-edit") {
        title.value = "Edit Post";
        submitBtnTitle.value = "Update";
      }
    };

    onMounted(() => {
      computedRouteName();

      if (router.currentRoute.value.name === "post-edit") {
        const id = router.currentRoute.value.params.id;

        post.value = store.getters["postsModule/getPost"](id);

        postImage.value = post.value?.photoURL
          ? post.value.photoURL
          : noImage.value;
      }
    });
    onUpdated(computedRouteName);

    return {
      title,
      submitBtnTitle,
      noImage,
      postImagePreview,
      postImage,
      postImageFile,
      postImageDelete,
      postImageOverSize,
      isSubmited,
      schema,
      post,
      router,
    };
  },
  methods: {
    ...mapActions({
      addPost: "postsModule/AddPost",
    }),
    uploadPreview(e: Event) {
      const target = e.target as HTMLInputElement;
      this.postImageFile = target.files ? target.files[0] : null;
      this.postImageOverSize = false;
      const size = GlobalService.FormatBytes(this.postImageFile.size);

      if ((size.type === "Bytes" || size.type === "KB") && size.number < 1024) {
        const reader: FileReader = new FileReader();

        reader.onloadend = () => {
          this.postImagePreview = reader.result;
        };

        reader.readAsDataURL(this.postImageFile);
      } else {
        this.postImageOverSize = true;
        this.postImageFile = null;
        this.postImagePreview = this.noImage;
      }
    },
    clearImage() {
      if (this.post.photoURL) {
        this.postImageDelete = true;
      }

      this.postImageFile = null;
      this.postImagePreview = this.noImage;
    },
    submit(form: IForm) {
      this.isSubmited = true;

      this.post.title = form.title;
      this.post.excerpt = form.excerpt;
      this.post.description = form.description;

      const callback = () => {
        this.isSubmited = false;
        this.router.push("/admin/posts");
      };

      if (this.postImageFile) {
        this.addPost({
          post: this.post,
          file: this.postImageFile,
          type: "upload",
        }).then(callback);
      } else if (this.postImageDelete) {
        this.addPost({
          post: this.post,
          type: "delete",
        }).then(() => {
          this.postImageDelete = false;
          callback();
        });
      } else {
        this.addPost({
          post: this.post,
        }).then(callback);
      }
    },
  },
});
</script>

// alex_s/ap-angular/src/app/admin/post-manage/post-manage.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { Post } from '../../shared/services/post/post';
import { PostService } from '../../shared/services/post/post.service';
import { GlobalService } from '../../shared/services/global/global.service';

@Component({
  selector: 'app-post-manage',
  templateUrl: './post-manage.component.html',
  styleUrls: ['./post-manage.component.scss']
})
export class PostManageComponent implements OnInit, OnDestroy {
  title: string;
  submitBtnTitle: string;
  postType: string;

  noImage = 'assets/images/site/no-image.svg';
  postImagePreview: string | ArrayBuffer;
  postImage: string | ArrayBuffer = this.noImage;
  postImageFile: File | null;
  postImageDelete = false;
  postImageOverSize = false;
  isSubmitted = false;
  loading = false;
  post: Post;

  postsSubscription: any;
  routeUrlSubscription: any;
  routeParamsSubscription: any;

  constructor(
    private route: ActivatedRoute,
    private fb: FormBuilder,
    private router: Router,
    private postService: PostService,
    private globalService: GlobalService
  ) { }

  postForm = this.fb.group({
    image: [''],
    title: ['', Validators.required],
    excerpt: [''],
    description: ['', Validators.required]
  });

  ngOnInit(): void {
    this.routeUrlSubscription = this.route.url.subscribe(data => {
      this.postType = data[1].path;

      if (this.postType === 'add') {
        this.title = 'Add New Post';
        this.submitBtnTitle = 'Create';

        this.fillPost(null);
      } else if (this.postType === 'edit') {
        this.title = 'Edit Post';
        this.submitBtnTitle = 'Update';

        this.routeParamsSubscription = this.route.params.subscribe(params => {
          if (params.id) {
            this.postsSubscription = this.postService.GetPost(params.id)
              .subscribe((post: Post) => {
                this.fillPost(post);
              });
          }
        });
      }
    });
  }

  ngOnDestroy(): void {
    this.routeUrlSubscription.unsubscribe();

    if (this.postType === 'edit') {
      this.routeParamsSubscription.unsubscribe();
      this.postsSubscription.unsubscribe();
    }
  }

  uploadPreview(event): void {
    this.postImageFile = event.target.files[0];
    this.postImageOverSize = false;
    const size = this.globalService.FormatBytes(this.postImageFile.size);

    if ( (size.type === 'Bytes' || size.type === 'KB') && size.number < 1024) {
      const reader: FileReader = new FileReader();

      reader.onloadend = () => {
        this.postImagePreview = reader.result;
      };

      reader.readAsDataURL(this.postImageFile);
    } else {
      this.postImageOverSize = true;
      this.postImageFile = null;
      this.postImagePreview = this.noImage;
    }
  }

  clearImage(): void {
    if (this.post.photoURL) {
      this.postImageDelete = true;
    }

    this.postImageFile = null;
    this.postImagePreview = this.noImage;
  }

  fillPost(post: Post): void {
    if (post) {
      this.post = {
        uid: post.uid,
        photoURL: post.photoURL,
        title: post.title,
        excerpt: post.excerpt,
        description: post.description
      };

      this.postImage = post.photoURL ? post.photoURL : this.noImage;
      this.postForm.controls.title.setValue(post.title);
      this.postForm.controls.excerpt.setValue(post.excerpt);
      this.postForm.controls.description.setValue(post.description);
    } else {
      this.post = {
        photoURL: '',
        title: '',
        excerpt: '',
        description: ''
      };

      this.postImage = this.noImage;
    }
  }

  onSubmit(): void {
    this.isSubmitted = true;

    if (this.postForm.status !== 'INVALID') {
      this.loading = true;

      this.post.title = this.postForm.controls.title.value;
      this.post.excerpt = this.postForm.controls.excerpt.value;
      this.post.description = this.postForm.controls.description.value;

      this.postService.SetPostData(this.post)
        .then((id: string) => {
          if (this.postImageFile) {
            this.globalService.UploadImage(this.postImageFile, id, 'posts-images', 'posts').then(() => {
              this.loading = false;
              this.router.navigate(['admin/posts']);
            });
          } else if (this.postImageDelete) {
            this.globalService.DeleteImage(id, 'posts-images', 'posts').then(() => {
              this.loading = false;
              this.postImageDelete = false;
              this.router.navigate(['admin/posts']);
            });
          } else {
            this.loading = false;
            this.router.navigate(['admin/posts']);
          }
        });
    }
  }
}

<div class="post-manage">
  <h2 class="page-title">Posts</h2>

  <form [formGroup]="postForm" class="form" [ngClass]="{submitted: isSubmitted}" (ngSubmit)="onSubmit()">
    <app-card>
      <ng-container header-title>{{ title }}</ng-container>

      <ng-container body>
        <div class="row">
          <div class="col-lg post-manage__image-wrap">
            <div class="form__upload">
              <div class="form__upload__image">
                <div class="form__upload__image__img"
                  [style.backgroundImage]="'url(' + (postImagePreview ? postImagePreview : postImage) + ')'">
                </div>
                <button *ngIf="postImage || postImagePreview" (click)="clearImage()" type="button"
                  class="form__upload__image__clear"><i class="las la-times"></i></button>
              </div>
              <div class="form__upload__btn">
                <input type="file" id="image" formControlName="image" (change)="uploadPreview($event)"
                  accept=".png,.jpg" />
                <label type="button" for="image" class="btn btn--gray">Upload Image</label>
              </div>
              <div class="form__upload__description" [ngClass]="{'form__upload__description--danger' : postImageOverSize}">
                Maximum upload image size: <span>1MB</span>
              </div>
            </div>
          </div>
          <div class="col-lg">
            <div class="form__group form__group--required">
              <label class="form__label" for="title">Title</label>
              <input type="text" id="title" class="form__element" formControlName="title" />
            </div>

            <div class="form__group">
              <label class="form__label" for="excerpt">Excerpt</label>
              <input type="text" id="excerpt" class="form__element" formControlName="excerpt" />
            </div>
          </div>
        </div>
        <br />
        <div class="form__group form__group--required">
          <label class="form__label" for="description">Description</label>
          <textarea id="description" class="form__element" formControlName="description"></textarea>
        </div>
      </ng-container>

      <ng-container footer>
        <div class="btn-group">
          <button [disabled]="loading" class="btn btn--blue" type="submit">{{ submitBtnTitle }}</button>
          <a class="btn btn--cancel" href="#" [routerLink]="loading ? [] : ['/admin/posts']">Cancel</a>
        </div>
      </ng-container>
    </app-card>
  </form>
</div>
