// alex_s/ap-vue/src/components/sorting-btn/index.vue
<template>
  <div class="sorting-btn">
    <i
      class="fa fa-long-arrow-down sort-btn__item"
      :class="{ 'sorting-btn__item--active': sortedBy === false }"
      aria-hidden="true"
    ></i>
    <i
      class="fa fa-long-arrow-up table__header__item__sort-btn__item"
      :class="{ 'sorting-btn__item--active': sortedBy === true }"
      aria-hidden="true"
    ></i>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";

export default defineComponent({
  props: {
    sortedBy: Boolean,
  },
});
</script>

// alex_s/ap-angular/src/app/shared/components/sorting-btn/sorting-btn.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-sorting-btn',
  templateUrl: './sorting-btn.component.html',
  styleUrls: ['./sorting-btn.component.scss']
})
export class SortingBtnComponent implements OnInit {
  @Input() sortedBy: boolean;

  constructor() { }

  ngOnInit(): void {
  }

}

<div class="sorting-btn">
    <i class="fa fa-long-arrow-down sort-btn__item"
        [ngClass]="{'sorting-btn__item--active' : sortedBy === false}" aria-hidden="true"></i>
    <i class="fa fa-long-arrow-up table__header__item__sort-btn__item"
        [ngClass]="{'sorting-btn__item--active' : sortedBy === true}" aria-hidden="true"></i>
</div>
