// alex_s/ap-vue/src/authorization/forgot-password/index.vue
<template>
  <div class="content__title">Reset Password</div>

  <Form
    class="form"
    @submit="sendPasswordResetEmail"
    :validation-schema="schema"
    v-slot="{ errors }"
  >
    <div class="form__description">
      Please enter your email address to request a password reset.
    </div>

    <div class="form__group form__group--required">
      <Field
        type="text"
        name="email"
        id="email"
        class="form__element"
        :class="{ 'is-invalid': errors.email }"
      />
    </div>

    <div class="form__submit form__submit--center">
      <button :disabled="isSubmited" class="btn btn--red" type="submit">
        Reset Password
      </button>
    </div>

    <div class="form__description">
      Go back to? <router-link to="/auth/sign-in">Sign In</router-link>
    </div>
  </Form>
</template>

<script lang="ts">
import { defineComponent, ref } from "vue";
import AuthService from "@/servises/auth";
import router from "@/router";

import { Form, Field } from "vee-validate";
import * as Yup from "yup";

interface IForm {
  email: string;
}

export default defineComponent({
  components: {
    Form,
    Field,
  },
  setup() {
    const schema = Yup.object().shape({
      email: Yup.string()
        .required("Email is required")
        .email("Email is invalid"),
    });
    const isSubmited = ref(false);

    return {
      schema,
      isSubmited,
    };
  },
  methods: {
    sendPasswordResetEmail(form: IForm) {
      this.isSubmited = true;

      AuthService.ForgotPassword(form.email)
        .then(() => {
          this.isSubmited = false;
          router.push("/auth/sign-in");
        })
        .catch(() => {
          this.isSubmited = false;
        });
    },
  },
});
</script>

// alex_s/ap-angular/src/app/auth/forgot-password/forgot-password.component.ts
import { Component, OnInit } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { AuthService } from '../../shared/services/auth/auth.service';

@Component({
  selector: 'app-forgot-password',
  templateUrl: './forgot-password.component.html',
  styleUrls: ['./forgot-password.component.scss']
})
export class ForgotPasswordComponent implements OnInit {
  isSubmitted: boolean = false;
  loading: boolean = false;

  constructor(private fb: FormBuilder, public authService: AuthService) { }

  userForm = this.fb.group({
    email: ['', [Validators.required, Validators.email]]
  })

  ngOnInit(): void {
  }

  onSubmit() {
    this.isSubmitted = true;

    if (this.userForm.status !== "INVALID") {
      this.loading = true;

      this.authService.ForgotPassword(this.userForm.controls.email.value)
        .then(() => {
          this.loading = false;
        });
    }
  }
}

<form [formGroup]="userForm" class="form" [ngClass]="{submitted: isSubmitted}" (ngSubmit)="onSubmit()">
  <div class="form__description">
    Please enter your email address to request a password reset.
  </div>

  <div class="form__group form__group--required">
    <input type="email" id="email" class="form__element" formControlName="email" />
  </div>

  <div class="form__submit form__submit--center">
    <button [disabled]="loading" class="btn btn--red" type="submit">Reset Password</button>
  </div>

  <div class="form__description">
    Go back to? <a routerLink="/sign-in">Sign in</a>
  </div>
</form>
