// alex_s/ap-angular/src/app/auth/verify-email/verify-email.component.ts
import { Component, OnInit } from '@angular/core';
import { AuthService } from '../../shared/services/auth/auth.service';

@Component({
  selector: 'app-verify-email',
  templateUrl: './verify-email.component.html',
  styleUrls: ['./verify-email.component.scss']
})
export class VerifyEmailComponent implements OnInit {

  constructor(public authService: AuthService) { }

  ngOnInit(): void {
  }

}

<div class="form">
  <div class="formGroup" *ngIf="authService.userData as user">
    <p class="text-center">We have sent a confirmation email to <strong>{{user.email}}</strong>.</p>
    <p class="text-center">Please check your email and click on the link to verfiy your email address.</p>
  </div>

  <div class="form__submit form__submit--center">
    <button class="btn btn--red" type="button" (click)="authService.SendVerificationMail()">Resend Verification Email</button>
  </div>

  <div class="form__description form__description--center">
    Go back to? <a routerLink="/sign-in">Sign in</a>
  </div>
</div>

// alex_s/ap-vue/src/authorization/verify-email/index.vue
<template>
  <div class="form">
    <div class="formGroup" v-if="user">
      <p class="text-center">
        We have sent a confirmation email to <strong>{{ user.email }}</strong
        >.
      </p>
      <p class="text-center">
        Please check your email and click on the link to verfiy your email
        address.
      </p>
    </div>

    <div class="form__submit form__submit--center">
      <button
        class="btn btn--red"
        type="button"
        @click="authService.SendVerificationMail()"
      >
        Resend Verification Email
      </button>
    </div>

    <div class="form__description form__description--center">
      Go back to? <router-link to="/auth/sign-in">Sign in</router-link>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import AuthService from "@/servises/auth";

export default defineComponent({
  setup() {
    const user = JSON.parse(localStorage.getItem("user") || "null");
    const authService = AuthService;

    return {
      user,
      authService,
    };
  },
});
</script>
