// alex_s/ap-angular/src/app/admin/profile/profile.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { UserService } from '../../shared/services/user/user.service';
import { AuthService } from '../../shared/services/auth/auth.service';
import { GlobalService } from '../../shared/services/global/global.service';
import { MustMatch } from '../../shared/validators/must-match.validator';

import { User } from '../../shared/services/user/user';

@Component({
  selector: 'app-profile',
  templateUrl: './profile.component.html',
  styleUrls: ['./profile.component.scss']
})
export class ProfileComponent implements OnInit, OnDestroy {
  noImage = 'assets/images/site/no-image.svg';
  userAvatarPreview: string | ArrayBuffer;
  userAvatar: string | ArrayBuffer = this.noImage;
  userAvatarFile: File | null;
  userAvatarDelete = false;
  isSubmitted = false;
  loading = false;
  usersSubscription: any;
  user: User;
  userId = '';
  tabState = 'GeneralInformation';
  passwordOld: string;
  password: string;
  passwordConfirm: string;

  constructor(
    private fb: FormBuilder,
    private userService: UserService,
    public authService: AuthService,
    private globalService: GlobalService
  ) { }

  userForm = this.fb.group({
    avatar: [''],
    name: ['', [Validators.required]],
    surname: ['', [Validators.required]],
    email: [{ value: '', disabled: true }, [Validators.required, Validators.email]],
    occupation: ['', [Validators.required]],
  });

  userChangePasswordForm = this.fb.group({
    passwordOld: ['', Validators.required],
    password: ['', Validators.required],
    passwordConfirm: ['', Validators.required]
  }, {
    validator: MustMatch('password', 'passwordConfirm')
  });

  ngOnInit(): void {
    this.loading = true;
    const id = JSON.parse(localStorage.getItem('user')).uid;

    this.usersSubscription = this.userService.GetUser(id)
      .subscribe((user: User) => {
        this.user = user;
        this.userForm.controls.name.setValue(user.name);
        this.userForm.controls.surname.setValue(user.surname);
        this.userForm.controls.email.setValue(user.email);
        this.userForm.controls.occupation.setValue(user.occupation);
        this.userId = user.uid;

        this.userAvatar = user.photoURL ? user.photoURL : this.noImage;

        this.loading = false;
      });
  }

  ngOnDestroy(): void {
    this.usersSubscription.unsubscribe();
  }

  uploadPreview(event): void {
    this.userAvatarFile = event.target.files[0];

    const reader: FileReader = new FileReader();

    reader.onloadend = () => {
      this.userAvatarPreview = reader.result;
    };

    reader.readAsDataURL(this.userAvatarFile);
  }

  clearAvatar(): void {
    if (this.user.photoURL) {
      this.userAvatarDelete = true;
    }

    this.userAvatarFile = null;
    this.userAvatarPreview = this.noImage;
  }

  switchTab(event: any, tabName: string): void {
    event.stopPropagation();
    event.preventDefault();

    this.tabState = tabName;
  }

  onSubmit(): void {
    this.isSubmitted = true;

    if (this.userForm.status !== 'INVALID') {
      this.loading = true;

      this.user.name = this.userForm.controls.name.value;
      this.user.surname = this.userForm.controls.surname.value;
      this.user.occupation = this.userForm.controls.occupation.value;

      this.userService.SetUserData(this.user)
        .then(() => {
          if (this.userAvatarFile) {
            this.globalService.UploadImage(this.userAvatarFile, this.user.uid, 'avatars', 'users').then(() => {
              this.loading = false;
            });
          } else if (this.userAvatarDelete) {
            this.globalService.DeleteImage(this.user.uid, 'avatars', 'users').then(() => {
              this.loading = false;
              this.userAvatarDelete = false;
            });
          } else {
            this.loading = false;
          }
        });
    }
  }

  onChangePassword(): void {
    this.isSubmitted = true;

    if (this.userChangePasswordForm.status !== 'INVALID') {
      this.loading = true;

      this.passwordOld = this.userChangePasswordForm.controls.passwordOld.value;
      this.password = this.userChangePasswordForm.controls.password.value;
      this.passwordConfirm = this.userChangePasswordForm.controls.passwordConfirm.value;

      this.authService.ChangePassword(this.passwordOld, this.user.email, this.password)
        .then(() => {
          this.loading = false;
        });
    }
  }
}

<div class="profile">
  <h2 class="page-title">My Profile</h2>

  <div class="row">
    <div class="col profile__sidebar">
      <div class="profile__card">
        <div class="profile__card__header">
          <div class="profile__card__header__inner">
            <div class="profile__card__user-avatar">
              <div class="profile__card__user-avatar__img" [style.backgroundImage]="'url(' + userAvatar + ')'"></div>
            </div>
            <div class="profile__card__user-name">
              <span *ngIf="user && user.name">{{ user.name }} </span>
              <span *ngIf="user && user.surname">{{ user.surname }}</span>
            </div>
            <div *ngIf="user && user.occupation" class="profile__card__user-occupation">{{ user.occupation }}</div>
          </div>
        </div>

        <nav class="profile__card__nav">
          <ul>
            <li>
              <a (click)="switchTab($event, 'GeneralInformation')" class="profile__card__nav__item" href="#"
                [ngClass]="{'profile__card__nav__item--active' : tabState === 'GeneralInformation'}">
                <i class="fa fa-user-circle" aria-hidden="true"></i>
                General Information
              </a>
            </li>
            <li>
              <a (click)="switchTab($event, 'ChangePassword')" class="profile__card__nav__item" href="#"
                [ngClass]="{'profile__card__nav__item--active' : tabState === 'ChangePassword'}">
                <i class="fa fa-user-secret" aria-hidden="true"></i>
                Change Password
              </a>
            </li>
            <li>
              <a class="profile__card__nav__item" href="#" [routerLink]="['/admin/posts/owner/user', userId]"
                routerLinkActive="profile__card__nav__item--active">
                <i class="fa fa-file-o" aria-hidden="true"></i>
                My Posts
              </a>
            </li>
          </ul>
        </nav>

        <div class="profile__card__footer">
          <button class="btn btn--red" type="button" (click)="authService.SignOut()">Logout</button>
        </div>
      </div>
    </div>
    <div class="col profile__content">
      <ng-template [ngIf]="tabState === 'GeneralInformation'">
        <form [formGroup]="userForm" class="form" [ngClass]="{'submitted' : isSubmitted}" (ngSubmit)="onSubmit()">
          <app-card>
            <ng-container header-title>General Information</ng-container>
            <ng-container body>
              <div class="row">
                <div class="col profile__content__left">
                  <div class="form__group">
                    <div class="form__upload">
                      <div class="form__upload__avatar">
                        <div class="form__upload__avatar__img"
                          [style.backgroundImage]="'url(' + (userAvatarPreview ? userAvatarPreview : userAvatar) + ')'">
                        </div>
                        <button (click)="clearAvatar()" type="button" class="form__upload__avatar__clear"><i
                            class="las la-times"></i></button>
                      </div>
                      <div class="form__upload__btn">
                        <input type="file" id="avatar" formControlName="avatar" (change)="uploadPreview($event)"
                          accept=".png,.jpg" />
                        <label type="button" for="avatar" class="btn btn--gray">Upload Avatar</label>
                      </div>
                      <div class="form__upload__description">Maximum upload image size: <span>1MB</span></div>
                    </div>
                  </div>
                </div>
                <div class="col">
                  <div class="form__group form__group--required">
                    <label class="form__label" for="name">Name</label>
                    <input type="text" id="name" class="form__element" formControlName="name" />
                  </div>

                  <div class="form__group form__group--required">
                    <label class="form__label" for="surname">Surname</label>
                    <input type="text" id="surname" class="form__element" formControlName="surname" />
                  </div>

                  <div class="form__group form__group--required">
                    <label class="form__label" for="email">Email</label>
                    <input type="email" id="email" class="form__element" formControlName="email" />
                  </div>

                  <div class="form__group form__group--required">
                    <label class="form__label" for="occupation">Occupation</label>
                    <input type="text" id="occupation" class="form__element" formControlName="occupation" />
                  </div>
                </div>
              </div>
            </ng-container>
            <ng-container footer>
              <button [disabled]="loading" class="btn btn--blue" type="submit">Update</button>
            </ng-container>
          </app-card>
        </form>
      </ng-template>

      <ng-template [ngIf]="tabState === 'ChangePassword'">
        <form [formGroup]="userChangePasswordForm" class="form" [ngClass]="{'submitted' : isSubmitted}" (ngSubmit)="onChangePassword()">
          <app-card>
            <ng-container header-title>Change Password</ng-container>
            <ng-container body>
              <div class="form__group form__group--required">
                <label class="form__label" for="passwordOld">Old Password</label>
                <input type="password" id="passwordOld" class="form__element" formControlName="passwordOld" />
              </div>

              <div class="form__group form__group--required">
                <label class="form__label" for="password">New Password</label>
                <input type="password" id="password" class="form__element" formControlName="password" />
              </div>

              <div class="form__group form__group--required">
                <label class="form__label" for="passwordConfirm">Confirm New Password</label>
                <input type="password" id="passwordConfirm" class="form__element" formControlName="passwordConfirm" />
              </div>
            </ng-container>

            <ng-container footer>
              <button [disabled]="loading" class="btn btn--blue" type="submit">Update</button>
            </ng-container>
          </app-card>
        </form>
      </ng-template>
    </div>
  </div>
</div>

// alex_s/ap-vue/src/admin/profile/index.vue
<template>
  <div class="profile">
    <h2 class="page-title">My Profile</h2>

    <div class="row">
      <div class="col profile__sidebar">
        <div class="profile__card">
          <div class="profile__card__header">
            <div class="profile__card__header__inner">
              <div class="profile__card__user-avatar">
                <div
                  class="profile__card__user-avatar__img"
                  :style="{
                    backgroundImage: `url(${
                      user?.photoURL ? user.photoURL : noImage
                    })`,
                  }"
                ></div>
              </div>
              <div class="profile__card__user-name">
                <span v-if="user && user.name">{{ user.name }}&nbsp;</span>
                <span v-if="user && user.surname">{{ user.surname }}</span>
              </div>
              <div
                v-if="user && user.occupation"
                class="profile__card__user-occupation"
              >
                {{ user.occupation }}
              </div>
            </div>
          </div>

          <nav class="profile__card__nav">
            <ul>
              <li>
                <a
                  @click="switchTab($event, 'GeneralInformation')"
                  class="profile__card__nav__item"
                  href="#"
                  :class="{
                    'profile__card__nav__item--active':
                      tabState === 'GeneralInformation',
                  }"
                >
                  <i class="fa fa-user-circle" aria-hidden="true"></i>
                  General Information
                </a>
              </li>
              <li>
                <a
                  @click="switchTab($event, 'ChangePassword')"
                  class="profile__card__nav__item"
                  href="#"
                  :class="{
                    'profile__card__nav__item--active':
                      tabState === 'ChangePassword',
                  }"
                >
                  <i class="fa fa-user-secret" aria-hidden="true"></i>
                  Change Password
                </a>
              </li>
              <li>
                <router-link
                  class="profile__card__nav__item"
                  :to="`/admin/posts/${user?.uid}`"
                >
                  <i class="fa fa-file-o" aria-hidden="true"></i>
                  My Posts
                </router-link>
              </li>
            </ul>
          </nav>

          <div class="profile__card__footer">
            <button class="btn btn--red" type="button" @click="signOut">
              Logout
            </button>
          </div>
        </div>
      </div>
      <div class="col-md profile__content">
        <UserForm v-show="tabState === 'GeneralInformation'" />

        <PasswordForm v-show="tabState === 'ChangePassword'" />
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent, computed, ref } from "vue";
import { useRouter } from "vue-router";
import { useStore, mapActions } from "vuex";

import UserForm from "./user-form/index.vue";
import PasswordForm from "./password-form/index.vue";

export default defineComponent({
  components: {
    UserForm,
    PasswordForm,
  },
  setup() {
    const store = useStore();
    const router = useRouter();
    const tabState = ref("GeneralInformation");

    return {
      tabState,
      router,
      user: computed(() => store.state.authModule.user),
      noImage: computed(() =>
        require("@/assets/images/site/no-image-white.svg")
      ),
    };
  },
  methods: {
    ...mapActions(["authModule/SignOut"]),
    signOut() {
      this["authModule/SignOut"]().then(() => {
        this.router.push("/auth/sign-in");
      });
    },
    switchTab(e: Event, tabName: string) {
      e.preventDefault();

      this.tabState = tabName;
    },
  },
});
</script>
