// alex_s/ap-vue/src/admin/users/user-manage/index.vue
<template>
  <div class="user-manage">
    <h2 class="page-title">Users</h2>

    <Form
      class="form"
      @submit="submit"
      :validation-schema="schema"
      :initial-values="user"
      v-slot="{ errors }"
    >
      <div class="card">
        <div class="card__header">
          <div class="card__title">{{ title }}</div>
        </div>

        <div class="card__body">
          <div v-if="!loading" class="row">
            <div class="col-md user-manage__image-wrap">
              <div class="form__upload">
                <div class="form__upload__image">
                  <div
                    class="form__upload__image__img"
                    :style="{
                      backgroundImage: `url(${
                        userImagePreview ? userImagePreview : userImage
                      }`,
                    }"
                  ></div>
                  <button
                    v-if="(userImage || userImagePreview) && permissionWrite"
                    type="button"
                    class="form__upload__image__clear"
                    @click="clearImage"
                  >
                    <i class="las la-times"></i>
                  </button>
                </div>
                <div class="form__upload__btn">
                  <input
                    type="file"
                    id="avatar"
                    :disabled="!permissionWrite || isSubmited"
                    accept=".png,.jpg"
                    @change="uploadPreview"
                  />
                  <label
                    type="button"
                    for="avatar"
                    class="btn btn--gray"
                    :class="{ 'btn--disabled': !permissionWrite || isSubmited }"
                  >
                    Upload Avatar
                  </label>
                </div>
                <div
                  class="form__upload__description"
                  :class="{
                    'form__upload__description--danger': userImageOverSize,
                  }"
                >
                  Maximum upload image size: <span>1MB</span>
                </div>
              </div>
            </div>
            <div class="col-md">
              <div class="row">
                <div class="col-md">
                  <div class="form__group form__group--required">
                    <label class="form__label" for="name">Name</label>
                    <Field
                      type="text"
                      name="name"
                      id="name"
                      class="form__element"
                      :class="{ 'is-invalid': errors.name }"
                      :readonly="!permissionWrite"
                    />
                  </div>

                  <div class="form__group form__group--required">
                    <label class="form__label" for="email">Email</label>
                    <Field
                      type="text"
                      name="email"
                      id="email"
                      class="form__element"
                      :class="{ 'is-invalid': errors.email }"
                      :readonly="true"
                    />
                  </div>
                </div>
                <div class="col-md">
                  <div class="form__group form__group--required">
                    <label class="form__label" for="surname">Surname</label>
                    <Field
                      type="text"
                      name="surname"
                      id="surname"
                      class="form__element"
                      :class="{ 'is-invalid': errors.surname }"
                      :readonly="!permissionWrite"
                    />
                  </div>

                  <div class="form__group form__group--required">
                    <label class="form__label" for="occupation">
                      Occupation
                    </label>
                    <Field
                      type="text"
                      name="occupation"
                      id="occupation"
                      class="form__element"
                      :class="{ 'is-invalid': errors.occupation }"
                      :readonly="!permissionWrite"
                    />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <div v-if="loading" class="loading loading--absolute">
            <i class="las la-spinner la-pulse la-6x la-fw"></i>
          </div>
        </div>

        <div class="card__footer">
          <div class="btn-group">
            <button
              :disabled="isSubmited || !permissionWrite"
              class="btn btn--blue"
              type="submit"
            >
              {{ submitBtnTitle }}
            </button>
            <router-link to="/admin/users" custom v-slot="{ href, navigate }">
              <a
                v-if="!isSubmited"
                :href="href"
                class="btn btn--cancel"
                @click="navigate"
              >
                Cancel
              </a>
              <button
                v-if="isSubmited"
                type="button"
                class="btn btn--cancel btn--disabled"
              >
                Cancel
              </button>
            </router-link>
          </div>
        </div>
      </div>
    </Form>
  </div>
</template>

<script lang="ts">
import { defineComponent, ref, computed, onUpdated, onMounted } from "vue";
import AuthService from "@/servises/auth";
import GlobalService from "@/servises/global";
import { useStore, mapActions } from "vuex";
import { useRouter } from "vue-router";

import { Form, Field } from "vee-validate";
import * as Yup from "yup";

interface IForm {
  email: string;
  name: string;
  surname: string;
  occupation: string;
}

export default defineComponent({
  components: {
    Form,
    Field,
  },
  setup() {
    const router = useRouter();
    const store = useStore();

    const title = ref("");
    const submitBtnTitle = ref("");

    const noImage = computed(() =>
      require("@/assets/images/site/no-image-white.svg")
    );
    const userImagePreview = ref();
    const userImage = ref();
    const userImageFile = ref();
    const userImageDelete = ref(false);
    const userImageOverSize = ref(false);
    const isSubmited = ref(false);
    const loading = ref(true);

    const user = ref();

    const schema = Yup.object().shape({
      email: Yup.string().required("Email is required"),
      name: Yup.string().required("Name is required"),
      surname: Yup.string().required("Surname is required"),
      occupation: Yup.string().required("Occupation is required"),
    });

    const computedRouteName = () => {
      if (router.currentRoute.value.name === "user-add") {
        title.value = "Add New User";
        submitBtnTitle.value = "Create";
        loading.value = false;
        userImage.value = noImage.value;
      } else if (router.currentRoute.value.name === "user-edit") {
        title.value = "Edit User";
        submitBtnTitle.value = "Update";
      }
    };

    const permissionWrite = computed(() => {
      const user = store.state.authModule.user;
      const id = router.currentRoute.value.params.id;

      if (user?.uid === id) {
        return true;
      } else {
        return user?.roles.includes("ROLE_SUPER_ADMIN");
      }
    });

    onMounted(() => {
      computedRouteName();

      if (router.currentRoute.value.name === "user-edit") {
        const id = router.currentRoute.value.params.id;

        AuthService.GetUserData(id)
          .then((res) => {
            const rUser = res.data();
            user.value = rUser;
            userImage.value = rUser?.photoURL ? rUser.photoURL : noImage.value;
            loading.value = false;
          })
          .catch(() => {
            loading.value = false;
          });
      }
    });
    onUpdated(() => {
      computedRouteName();
    });

    return {
      title,
      submitBtnTitle,
      noImage,
      userImagePreview,
      userImage,
      userImageFile,
      userImageDelete,
      userImageOverSize,
      permissionWrite,
      isSubmited,
      loading,
      schema,
      user,
      router,
    };
  },
  methods: {
    ...mapActions({
      getAll: "usersModule/GetAll",
      editUser: "usersModule/EditUser",
    }),
    submit(form: IForm) {
      this.isSubmited = true;
      this.user.name = form.name;
      this.user.surname = form.surname;
      this.user.occupation = form.occupation;

      const callback = () => {
        this.isSubmited = false;
        this.router.push("/admin/users");
      };

      if (this.userImageFile) {
        this.editUser({
          user: this.user,
          file: this.userImageFile,
          type: "upload",
        }).then(callback);
      } else if (this.userImageDelete) {
        this.editUser({
          user: this.user,
          type: "delete",
        }).then(() => {
          this.userImageDelete = false;
          callback();
        });
      } else {
        this.editUser({
          user: this.user,
        }).then(callback);
      }
    },

    clearImage() {
      if (this.user.photoURL) {
        this.userImageDelete = true;
      }

      this.userImageFile = null;
      this.userImagePreview = this.noImage;
    },

    uploadPreview(e: Event) {
      const target = e.target as HTMLInputElement;
      this.userImageFile = target.files ? target.files[0] : null;
      this.userImageOverSize = false;
      const size = GlobalService.FormatBytes(this.userImageFile.size);

      if ((size.type === "Bytes" || size.type === "KB") && size.number < 1024) {
        const reader: FileReader = new FileReader();

        reader.onloadend = () => {
          this.userImagePreview = reader.result;
        };

        reader.readAsDataURL(this.userImageFile);
      } else {
        this.userImageOverSize = true;
        this.userImageFile = null;
        this.userImagePreview = this.noImage;
      }
    },
  },
});
</script>

// alex_s/ap-angular/src/app/admin/user-manage/user-manage.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Router, ActivatedRoute } from '@angular/router';
import { User } from '../../shared/services/user/user';
import { UserService } from '../../shared/services/user/user.service';
import { GlobalService } from '../../shared/services/global/global.service';

@Component({
  selector: 'app-user-manage',
  templateUrl: './user-manage.component.html',
  styleUrls: ['./user-manage.component.scss']
})
export class UserManageComponent implements OnInit, OnDestroy {
  title: string;
  submitBtnTitle: string;
  userType: string;

  noImage: string = 'assets/images/site/no-image.svg';
  userImagePreview: string | ArrayBuffer;
  userImage: string | ArrayBuffer = this.noImage;
  userImageFile: File | null;
  userImageDelete: boolean = false;
  userImageOverSize: boolean = false;
  isSubmitted: boolean = false;
  loading: boolean = false;
  user: User;
  currentUserRoles: Array<string> = [];

  currentUserSubscription: any;
  userSubscription: any;
  routeUrlSubscription: any;
  routeParamsSubscription: any;

  alertOptions = {
    autoClose: false,
    keepAfterRouteChange: false
  };

  constructor(
    private route: ActivatedRoute,
    private fb: FormBuilder,
    private router: Router,
    private userService: UserService,
    private globalService: GlobalService
  ) { }

  userForm = this.fb.group({
    avatar: [''],
    name: ['', [Validators.required]],
    surname: ['', [Validators.required]],
    email: [{ value: '', disabled: true }, [Validators.required, Validators.email]],
    occupation: ['', [Validators.required]],
  })


  ngOnInit(): void {
    this.loading = true;
    const id = JSON.parse(localStorage.getItem('user')).uid;

    this.currentUserSubscription = this.userService.GetUser(id)
      .subscribe((user: User) => {
        this.currentUserRoles = user.roles;

        this.loading = false;
      });

    this.routeUrlSubscription = this.route.url.subscribe(data => {
      this.userType = data[1].path;

      if (this.userType === 'add') {
        this.title = 'Add New User';
        this.submitBtnTitle = 'Create';

        this.fillPost(null);
      } else if (this.userType === 'edit') {
        this.title = 'Edit User';
        this.submitBtnTitle = 'Update';

        this.routeParamsSubscription = this.route.params.subscribe(params => {
          if (params.id) {
            this.userSubscription = this.userService.GetUser(params.id)
              .subscribe((user: User) => {
                this.fillPost(user);
              });
          }
        });
      }
    });
  }

  ngOnDestroy(): void {
    this.currentUserSubscription.unsubscribe();
    this.routeUrlSubscription.unsubscribe();

    if (this.userType === 'edit') {
      this.routeParamsSubscription.unsubscribe();
      this.userSubscription.unsubscribe();
    }
  }

  uploadPreview(event) {
    this.userImageFile = event.target.files[0];
    this.userImageOverSize = false;
    const size = this.globalService.FormatBytes(this.userImageFile.size);

    if ( (size.type === "Bytes" || size.type === "KB") && size.number < 1024) {
      const reader: FileReader = new FileReader();

      reader.onloadend = () => {
        this.userImagePreview = reader.result;
      }

      reader.readAsDataURL(this.userImageFile);
    } else {
      this.userImageOverSize = true;
      this.userImageFile = null;
      this.userImagePreview = this.noImage;
    }
  }

  clearImage() {
    if (this.user.photoURL) {
      this.userImageDelete = true;
    }

    this.userImageFile = null;
    this.userImagePreview = this.noImage;
  }

  fillPost(user: User): void {
    if (user) {
      this.user = user;

      this.userForm.controls.name.setValue(user.name);
      this.userForm.controls.surname.setValue(user.surname);
      this.userForm.controls.email.setValue(user.email);
      this.userForm.controls.occupation.setValue(user.occupation);
      this.userImage = user.photoURL ? user.photoURL : this.noImage;
    } else {
      this.user = { uid: '', name: '', surname: '', email: '', occupation: '', photoURL: '' };
      this.userImage = this.noImage;
    }
  }

  getPermission() {
    return !this.currentUserRoles.includes('ROLE_SUPER_ADMIN');
  }

  onSubmit() {
    this.isSubmitted = true;

    if (this.userForm.status !== "INVALID") {
      this.loading = true;

      this.user.name = this.userForm.controls.name.value;
      this.user.surname = this.userForm.controls.surname.value;
      this.user.occupation = this.userForm.controls.occupation.value;

      this.userService.SetUserData(this.user)
        .then(() => {
          if (this.userImageFile) {
            this.globalService.UploadImage(this.userImageFile, this.user.uid, 'avatars', 'users').then(() => {
              this.loading = false;
              this.router.navigate(['admin/users']);
            })
          } else if (this.userImageDelete) {
            this.globalService.DeleteImage(this.user.uid, 'avatars', 'users').then(() => {
              this.loading = false;
              this.userImageDelete = false;
              this.router.navigate(['admin/users']);
            });
          } else {
            this.loading = false;
            this.router.navigate(['admin/users']);
          }
        });
    }
  }
}

<div class="user-manage">
  <h2 class="page-title">Users</h2>

  <form [formGroup]="userForm" class="form" [ngClass]="{submitted: isSubmitted}" (ngSubmit)="onSubmit()">
    <app-card>
      <ng-container header-title>{{ title }}</ng-container>

      <ng-container body>
        <div class="row">
          <div class="col-md user-manage__image-wrap">
            <div class="form__upload">
              <div class="form__upload__image">
                <div class="form__upload__image__img"
                  [style.backgroundImage]="'url(' + (userImagePreview ? userImagePreview : userImage) + ')'">
                </div>
                <button *ngIf="userImage || userImagePreview" (click)="clearImage()" type="button"
                  class="form__upload__image__clear"><i class="las la-times"></i></button>
              </div>
              <div class="form__upload__btn">
                <input type="file" id="avatar" formControlName="avatar" (change)="uploadPreview($event)"
                  accept=".png,.jpg" />
                <label type="button" for="avatar" class="btn btn--gray">Upload Avatar</label>
              </div>
              <div class="form__upload__description" [ngClass]="{'form__upload__description--danger' : userImageOverSize}">
                Maximum upload image size: <span>1MB</span>
              </div>
            </div>
          </div>
          <div class="col-md">
            <div class="row">
              <div class="col-md">
                <div class="form__group form__group--required">
                  <label class="form__label" for="name">Name</label>
                  <input [readonly]="getPermission()" type="text" id="name" class="form__element" formControlName="name" />
                </div>

                <div class="form__group form__group--required">
                  <label class="form__label" for="email">Email</label>
                  <input [readonly]="getPermission()" type="text" id="email" class="form__element" formControlName="email" />
                </div>
              </div>
              <div class="col-md">
                <div class="form__group form__group--required">
                  <label class="form__label" for="surname">Surname</label>
                  <input [readonly]="getPermission()" type="text" id="surname" class="form__element" formControlName="surname" />
                </div>

                <div class="form__group form__group--required">
                  <label class="form__label" for="occupation">Occupation</label>
                  <input [readonly]="getPermission()" type="text" id="occupation" class="form__element" formControlName="occupation" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </ng-container>

      <ng-container footer>
        <div class="btn-group">
          <button [disabled]="loading || getPermission()" class="btn btn--blue" type="submit">{{ submitBtnTitle }}</button>
          <a class="btn btn--cancel" href="#" [routerLink]="loading ? [] : ['/admin/users']">Cancel</a>
        </div>
      </ng-container>
    </app-card>
  </form>
</div>
